In [1]:
import pandas as pd

df_gene_single_dbeta = pd.read_csv("result/GSE243529_aba/dbeta.csv")
df_gene_single_dbeta

      Unnamed: 0     dbeta     gene  feature
0     cg10222734 -0.010651     A1CF    5'UTR
1     cg11139127 -0.009722      A2M     Body
2     cg23546356 -0.016178    A2ML1  TSS1500
3     cg13001012 -0.008898    AADAC  TSS1500
4     cg00309402 -0.022852    AADAT    3'UTR
...          ...       ...      ...      ...
7899  cg21317279  0.009295    ZNRD1     Body
7900  cg21918728 -0.008992    ZNRF3     Body
7901  cg10659886  0.027345  ZSCAN18     Body
7902  cg02286335  0.007187    ZWINT   TSS200
7903  cg03100196  0.003925      ZYX  TSS1500

[7904 rows x 4 columns]

In [2]:
df_gene_single_dbeta_threshold = df_gene_single_dbeta[abs((df_gene_single_dbeta['dbeta'])) > 0.02]
print(df_gene_single_dbeta_threshold,df_gene_single_dbeta_threshold.shape)


df_gene_single_dbeta_threshold_hyper = df_gene_single_dbeta_threshold[df_gene_single_dbeta_threshold['dbeta']>0]
print(df_gene_single_dbeta_threshold_hyper,df_gene_single_dbeta_threshold_hyper.shape)


df_gene_single_dbeta_threshold_hyper_TSS = df_gene_single_dbeta_threshold_hyper.loc[(df_gene_single_dbeta_threshold_hyper['feature'] == 'TSS200') | (df_gene_single_dbeta_threshold_hyper['feature'] == 'TSS1500')]
print(df_gene_single_dbeta_threshold_hyper_TSS,df_gene_single_dbeta_threshold_hyper_TSS.shape)

      Unnamed: 0     dbeta     gene feature
4     cg00309402 -0.022852    AADAT   3'UTR
22    cg10118456  0.028641    ABCC1    Body
35    cg13460556  0.024486    ABHD2    Body
41    cg15626105 -0.026561   ABI3BP    Body
42    cg02915920  0.021758     ABL1    Body
...          ...       ...      ...     ...
7860  cg01672042  0.041204   ZNF423    Body
7872  cg14269096 -0.032189   ZNF532   5'UTR
7886  cg20671910  0.025048   ZNF687    Body
7887  cg07000116  0.023883   ZNF689    Body
7901  cg10659886  0.027345  ZSCAN18    Body

[987 rows x 4 columns] (987, 4)
      Unnamed: 0     dbeta     gene feature
22    cg10118456  0.028641    ABCC1    Body
35    cg13460556  0.024486    ABHD2    Body
42    cg02915920  0.021758     ABL1    Body
44    cg12020464  0.027008      ABO    Body
46    cg07660627  0.035745    ACACA    Body
...          ...       ...      ...     ...
7825  cg10687936  0.030197   ZNF148   5'UTR
7860  cg01672042  0.041204   ZNF423    Body
7886  cg20671910  0.025048   ZNF687    Body
7887  cg07000116  0.023883   ZNF689    Body
7901  cg10659886  0.027345  ZSCAN18    Body

[642 rows x 4 columns] (642, 4)
      Unnamed: 0     dbeta     gene  feature
50    cg10523679  0.021226    ACADM  TSS1500
73    cg20707765  0.024253    ACSL5  TSS1500
258   cg19536664  0.030384   ALOX12  TSS1500
298   cg14904662  0.020543     ANK1  TSS1500
395   cg01699630  0.024147     ARG1  TSS1500
...          ...       ...      ...      ...
6782  cg16688533  0.040679     STC1  TSS1500
6843  cg03681335  0.029692  SULT1C2  TSS1500
6853  cg15100599  0.023953    SUSD4  TSS1500
7067  cg02569115  0.028042    TIMP2  TSS1500
7599  cg09276451  0.021343     VASN  TSS1500

[92 rows x 4 columns] (92, 4)

In [5]:
df_gene_single_dbeta_threshold_hyper_TSS = df_gene_single_dbeta_threshold_hyper_TSS[["Unnamed: 0","dbeta","gene"]]
df_gene_single_dbeta_threshold_hyper_TSS.to_csv("result/GSE243529_aba/dbeta_0.8_abs_0.02_hyper_TSS.csv",index=False)

In [6]:

df_gene_single_dbeta_threshold_hyper_TSS['gene'].to_csv("result/GSE243529_aba/dbeta_0.8_abs_0.02_hyper_TSS_genelist.csv",index=False)