### Calculate delta beta

In [1]:
import pandas as pd
df=pd.read_csv('C:/Users/Administrator/Documents/all_beta_normalized.csv')
df.rename(columns={'Unnamed: 0': 'ID'}, inplace=True)

In [31]:
#[0~349419,1~94]>>normal
NM=df.iloc[0:,1:95]
NM=NM.T
NM=NM.drop_duplicates(keep='first')
#NM

In [32]:
# Computing IQR
NM_Q1 = NM.quantile(0.25)
NM_Q3 = NM.quantile(0.75)
NM_IQR = NM_Q3 - NM_Q1
NM_upper_fence=NM_Q3+NM_IQR*1.5
NM_lower_fence=NM_Q1-NM_IQR*1.5

In [33]:
print(NM_upper_fence)
print(NM_lower_fence)

0         0.897802
1         0.917274
2         0.237940
3         0.057615
4         0.591092
            ...
349415    0.989638
349416    0.988131
349417    0.192597
349418    0.091294
349419    0.930342
Length: 349420, dtype: float64
0         0.787742
1         0.625942
2        -0.037230
3         0.005383
4         0.187752
            ...
349415    0.927224
349416    0.906427
349417   -0.012122
349418    0.004710
349419    0.785885
Length: 349420, dtype: float64

In [118]:
NM_with_no_outlier = NM[(NM>NM_lower_fence)&(NM<NM_upper_fence)]
NM_with_no_outlier

,0,1,2,3,4,5,6,7,8,9,...,349410,349411,349412,349413,349414,349415,349416,349417,349418,349419
1,0.825079,0.690023,0.095879,0.037414,0.393330,0.009331,0.328442,0.942621,0.031717,0.095881,...,NaN,0.020601,0.072356,0.968504,0.381649,0.950538,0.959770,0.071075,0.044393,0.840609
3,0.836188,0.802989,0.030527,0.028130,0.278496,0.011361,0.249862,0.950659,0.029557,0.047822,...,0.722136,0.014369,0.040898,0.972370,0.401094,0.950720,0.935633,0.051070,0.038378,0.848534
5,0.855953,0.744400,0.058828,0.036667,0.354795,0.013282,0.333120,0.962022,0.021522,0.068462,...,0.661542,0.011254,0.062394,0.975291,0.394045,0.955993,0.956899,0.052173,0.051068,0.837635
7,0.856379,0.826541,0.103293,0.026973,0.371494,0.007895,0.365394,0.970061,0.011432,0.108350,...,0.841919,0.020804,0.082844,0.976512,0.420015,0.956690,0.947483,0.082928,0.061392,0.839505
9,0.833668,0.683470,0.054348,0.032372,0.372948,0.016698,0.356951,0.962299,0.019325,0.057746,...,0.706839,0.016967,0.047750,0.961957,0.279808,0.947600,0.956285,0.097815,0.050559,0.852883
11,0.836432,0.822242,0.102374,0.027366,0.424968,0.012377,0.335873,0.953207,0.031495,0.068694,...,0.652210,0.022727,0.068590,0.966042,0.200496,0.948253,0.941275,0.144147,0.047999,0.848574
13,0.827324,0.638978,0.084485,0.026462,0.423032,0.012863,0.383200,0.960038,0.021668,0.099760,...,0.673899,0.004438,0.076907,0.980168,0.394275,0.958505,0.938936,0.104969,0.036908,0.821904
15,0.879485,0.743948,0.123488,0.051002,0.391704,0.015826,0.307079,0.961126,0.027604,0.086808,...,0.666540,0.016765,0.061027,0.971755,0.404083,0.966815,0.951144,0.141579,0.039893,0.869046
17,0.859840,0.799018,NaN,0.040978,0.458908,0.007412,0.357335,NaN,0.020774,0.068564,...,0.737778,0.014035,0.046924,0.961638,0.240451,0.976706,0.963082,0.192042,0.043394,0.863199
19,0.843561,0.879799,0.095415,0.034248,0.450654,0.016908,0.359306,0.957072,0.041402,0.054925,...,0.668933,0.023262,0.077330,0.969368,0.361965,0.966931,0.950995,0.077992,0.061470,0.849000
21,0.858686,0.722351,0.101673,0.019729,0.417154,0.009603,0.371913,NaN,0.021291,0.131770,...,NaN,0.013069,0.052955,0.972768,0.199563,0.957494,0.946345,0.088407,0.030744,NaN
23,0.856681,0.801518,0.094825,0.021036,0.412242,0.016673,0.329358,0.948415,0.034448,0.073679,...,0.731306,NaN,0.118482,0.963522,0.314691,0.963806,0.946031,0.127971,0.083236,0.875267
25,0.853802,0.805990,0.163737,0.031733,0.503273,0.017331,0.409960,0.955782,0.021202,0.095706,...,0.725501,0.022556,0.087346,0.971876,0.231821,0.978004,0.949672,0.143247,0.031816,0.850818
27,0.829881,0.657494,0.115785,0.028807,0.373232,0.014899,0.319658,0.961941,0.043838,0.083021,...,0.744528,0.017741,0.064686,0.962887,0.352907,0.950347,0.960643,0.093083,0.032906,0.875126
29,0.867561,0.776135,0.168661,0.026061,0.396522,0.007482,0.402313,0.957782,0.023676,0.122989,...,0.818297,0.013201,0.093781,0.975103,0.458359,0.954649,0.959371,0.122524,0.040843,0.850912
31,0.798390,0.746824,0.093139,0.024840,0.297803,0.008352,0.325618,0.964997,0.003892,0.073565,...,NaN,0.013368,0.050939,0.948302,0.295826,NaN,0.934908,0.084009,0.037743,0.822582
33,0.859955,0.799092,0.137620,0.022943,0.409038,0.008149,0.336404,0.950558,0.035573,0.060881,...,0.733141,0.020863,0.057066,0.967625,0.430929,0.955900,0.962165,0.070522,0.050426,0.874686
35,0.846052,0.818770,0.236883,0.022294,0.389598,0.013943,0.382131,0.938187,0.028306,0.058173,...,0.637604,0.028161,0.088899,0.973372,0.304576,0.954562,0.960235,0.080305,0.039359,0.851498
37,0.854138,0.793819,0.157991,0.037337,0.435855,0.017850,0.373266,0.951513,0.026539,0.052244,...,0.717505,0.021116,0.087594,0.948881,0.383996,0.949588,0.958085,0.073651,0.064146,0.853514
39,0.863063,0.820834,0.131882,0.026408,0.360605,0.009957,0.388568,0.972394,0.020984,0.107902,...,0.756974,0.006600,0.067773,0.969551,0.326366,0.953044,0.960422,0.083119,0.032435,0.830837
41,0.827856,0.788106,0.078876,0.025099,0.314913,0.024074,0.321146,0.960235,0.038698,0.073908,...,0.671714,0.024362,0.064346,0.956987,0.362071,0.944827,0.937441,0.074904,0.053055,0.808988
43,0.837576,0.811352,NaN,0.039658,0.462359,0.019092,0.420780,0.951068,0.008660,0.130459,...,0.702157,0.018858,0.079616,0.967055,0.409286,0.958750,0.954043,0.155919,0.047931,0.845297
45,0.860345,0.743655,0.101945,0.035915,0.475171,0.019235,0.373692,0.951741,0.026201,0.067497,...,0.706123,0.019141,0.085248,0.985110,0.326585,0.961150,0.936281,0.101427,0.051574,0.878279
47,0.889648,0.843687,0.152962,0.022074,0.353244,0.008699,0.318714,0.951716,0.012177,0.093051,...,0.754286,0.026489,0.046101,0.951078,0.308291,0.975027,0.961584,0.079324,0.047938,0.831663
49,0.853983,0.687978,0.052249,0.037080,0.259046,0.016734,0.275323,0.955358,0.017760,0.063870,...,0.776866,0.007661,0.046507,0.970441,0.414703,0.935276,0.927701,0.038401,0.019913,0.886602
51,0.862018,0.752674,0.178423,0.033505,0.428961,0.008148,0.333506,0.963869,0.016450,0.078778,...,0.736427,0.023858,0.051401,0.974608,0.266620,0.966526,0.950546,0.120151,0.025531,0.880047
53,0.833490,0.787252,0.071917,0.028226,0.290347,0.018457,0.318798,0.954726,0.017600,0.078479,...,0.786627,0.011994,0.063127,0.955570,0.435888,0.956990,0.944462,0.043911,0.042174,0.873958
55,0.855037,0.802741,0.069676,0.031916,0.378887,0.016819,0.315923,0.943393,0.019552,0.101038,...,0.610156,0.024786,0.043671,0.958070,0.331683,0.968016,0.956128,0.140240,0.040117,0.815414
57,0.872947,0.809145,0.198456,0.032722,0.578967,0.017776,0.403467,0.946968,0.023315,0.058039,...,0.818200,0.023491,0.053343,0.969465,0.248435,0.974050,0.935258,0.099246,0.049689,0.838576
59,0.842851,0.806904,0.089120,0.024797,0.334096,0.009016,0.341368,0.950622,0.033169,0.077451,...,0.842564,0.024825,0.069960,0.959467,0.464873,0.951520,0.940250,0.064305,0.057546,0.869638
61,0.820195,0.733462,0.030161,0.015926,0.265348,0.004503,0.243491,0.949820,0.018882,0.044978,...,0.632351,0.012555,0.047900,0.968624,NaN,0.952747,0.949732,0.040928,0.060541,0.919811
63,0.840695,0.741443,0.036196,0.024113,0.404813,0.006940,0.358667,0.936984,0.027387,0.050042,...,0.681147,0.029173,0.048667,0.954651,0.411577,0.966981,0.948148,0.052490,0.052846,NaN
65,0.855099,0.729638,0.062241,0.050702,0.356697,0.018869,0.335802,0.949896,0.027771,0.102335,...,0.730981,0.024012,0.089764,0.954486,NaN,0.952765,0.965964,0.064990,0.075088,0.924960
67,0.828148,0.810555,0.023561,0.035864,0.258234,0.013014,NaN,0.970232,0.026942,0.077456,...,0.647565,0.017066,0.063119,0.966673,NaN,0.947095,0.951342,0.041140,0.050616,0.917843
69,0.804086,0.836770,0.032307,0.022438,0.295875,0.021561,0.244070,0.955393,0.035042,0.072788,...,0.765366,0.014655,0.063475,0.939163,NaN,0.950782,0.939807,0.051533,0.075879,NaN
71,0.827806,0.761167,0.062033,0.050914,0.338167,0.010560,0.311373,0.951152,0.022312,0.097483,...,0.766598,0.015977,0.094392,0.961329,0.381197,0.948647,0.951295,0.061040,0.060328,0.857455
73,0.852606,0.768365,0.226558,0.038677,0.443824,0.016543,0.317259,0.944363,0.028155,NaN,...,0.749615,NaN,0.071358,0.960912,NaN,0.961119,0.942991,0.121049,0.064918,0.865373
75,0.840909,0.718593,0.070265,0.024541,0.339842,0.012168,0.304294,0.949424,0.021257,0.074864,...,0.725219,0.022353,0.056672,0.966879,0.519641,0.956756,0.941839,0.060662,0.054250,0.911779
77,0.830618,0.816404,0.082564,0.030972,0.476943,0.015556,0.405322,0.957444,0.014376,0.109896,...,0.717021,0.019373,0.029873,0.962897,0.349174,0.971497,0.961073,0.144568,0.076558,0.896965
79,0.823980,0.783838,0.037050,0.031770,0.272864,0.011076,0.321759,0.962223,0.016155,0.059362,...,0.707109,0.021637,0.039668,0.947244,0.407483,0.954214,0.936691,0.037947,0.037450,NaN
81,0.822444,0.715821,0.076239,0.046223,0.315364,0.017350,0.290381,0.943433,0.014308,0.067306,...,0.780934,0.017425,0.094630,0.976167,0.315924,0.939917,0.936130,0.084859,0.065065,0.829986
83,0.834585,0.776409,0.120700,0.042108,0.506673,0.020916,0.320445,0.951218,0.018409,0.063189,...,0.761809,0.021080,0.051642,0.973405,0.311661,0.965939,0.924180,0.086033,0.026873,0.848440
85,0.832854,0.729086,0.038624,NaN,0.358996,0.027066,0.255889,0.949717,0.011885,0.105808,...,0.838803,0.022133,0.077882,0.942561,0.407165,0.937166,0.920909,0.065576,0.034966,0.877075
87,0.821732,0.700392,0.088332,0.055834,0.469807,0.013512,0.275795,0.942322,0.021849,0.082735,...,0.773025,0.020912,0.078208,0.971817,0.346940,0.951148,0.928063,0.080380,0.060104,0.852706
89,0.826682,0.763133,0.084242,NaN,0.475843,0.018562,0.348141,NaN,0.015064,NaN,...,0.745787,0.014974,0.066723,NaN,0.358380,0.967107,0.913662,0.111503,0.026862,0.851809
91,0.848220,0.736921,0.168672,0.038641,0.401205,0.021737,0.327146,0.951536,0.008762,0.076844,...,0.781652,0.018486,0.081010,0.970950,0.255112,0.955644,NaN,0.091365,0.018549,0.829832
93,0.878082,0.853359,0.100633,0.015039,0.519828,0.008414,0.426431,0.966761,0.009777,0.053228,...,0.677315,0.008254,0.053357,0.979070,0.271041,0.974669,0.961720,0.138419,0.023440,0.847393

In [35]:
#tumor
TM=df.iloc[0:,95:]
TM=TM.T
TM=TM.drop_duplicates(keep='first')
#TM

In [36]:
# Computing IQR
TM_Q1 = TM.quantile(0.25)
TM_Q3 = TM.quantile(0.75)
TM_IQR = TM_Q3 - TM_Q1
TM_upper_fence=TM_Q3+TM_IQR*1.5
TM_lower_fence=TM_Q1-TM_IQR*1.5

In [37]:
print(TM_upper_fence)
print(TM_lower_fence)

0         0.927305
1         0.988088
2         1.078788
3         0.088298
4         1.046499
            ...
349415    0.995151
349416    1.009465
349417    0.456836
349418    0.100155
349419    1.047942
Length: 349420, dtype: float64
0         0.789469
1         0.598780
2        -0.253640
3         0.002930
4        -0.010076
            ...
349415    0.925620
349416    0.855000
349417   -0.146117
349418    0.002818
349419    0.621256
Length: 349420, dtype: float64

In [117]:
TM_with_no_outlier = TM[(TM>TM_lower_fence)&(TM<TM_upper_fence)]
TM_with_no_outlier

,0,1,2,3,4,5,6,7,8,9,...,349410,349411,349412,349413,349414,349415,349416,349417,349418,349419
95,0.848640,0.835849,0.689860,0.026053,0.307428,0.013018,0.257798,0.948132,0.028677,0.050876,...,0.887464,0.035446,0.035701,0.930703,0.419212,0.948011,0.918874,0.063710,0.065267,0.809488
97,NaN,0.736250,0.091482,0.034979,0.438765,0.016418,0.487702,0.965503,0.008324,0.112029,...,0.592755,0.015368,0.026208,0.972626,0.300779,0.943832,0.886095,0.059815,0.034590,0.762308
99,NaN,NaN,0.789614,0.050414,0.694599,0.010383,0.752390,0.951136,0.025810,0.041456,...,0.801736,0.039249,0.032027,0.933482,0.192633,0.958028,0.900685,NaN,0.057278,0.897833
101,0.859208,0.845890,0.322008,0.041157,0.762746,0.010804,0.726420,0.956437,0.014983,0.063617,...,0.914115,0.026152,0.056730,0.953711,0.881102,0.960617,0.937151,NaN,0.099336,0.889068
103,0.888833,0.857176,0.428933,0.026791,0.502058,0.013143,0.564766,0.932658,0.018421,0.047962,...,0.831461,0.019649,0.042828,0.935870,0.517300,0.972264,0.942881,0.066790,0.050801,0.907839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,0.901550,0.864090,0.788893,0.053580,0.799111,0.017766,0.255841,0.946003,0.023425,0.103054,...,0.933226,0.048002,0.061864,0.958277,0.907994,0.960415,0.903175,0.318862,0.083533,0.889068
883,0.873928,0.878295,0.566003,0.037539,0.654631,0.014330,0.713082,0.978794,0.015606,0.155615,...,0.840340,0.033939,0.059825,0.969872,0.356385,0.965732,0.956787,0.358653,0.056394,0.852856
885,0.820407,0.699745,0.648568,0.063686,0.785799,0.011745,0.618195,0.959959,0.016112,0.126817,...,0.877494,0.035935,0.062544,0.947906,0.558346,0.966887,0.949065,0.223531,0.073767,0.903576
887,0.880965,0.851946,0.755152,0.067983,0.709136,0.013847,0.749643,0.962288,0.036406,0.122496,...,0.889202,0.037331,0.071570,0.939159,0.785912,0.971332,0.932598,0.232292,0.086748,0.926840
889,0.866919,0.784683,0.503848,0.053181,0.452765,0.015661,0.474667,0.950399,0.021407,0.275792,...,0.816753,0.044883,0.054991,0.956633,0.594033,0.967507,0.887922,0.107879,0.029125,0.842634

In [10]:
#data=pd.DataFrame(NM_with_no_outlier.T).join(TM_with_no_outlier.T)
#data

In [120]:
#計算normal平均值
NM_avg=NM_with_no_outlier.mean(skipna = True)
NM_avg

0         0.843970
1         0.769853
2         0.099663
3         0.031946
4         0.389191
            ...
349415    0.957445
349416    0.946883
349417    0.090105
349418    0.047211
349419    0.858512
Length: 349420, dtype: float64

In [53]:
#計算delta beta
dSub=(TM_with_no_outlier.T).subtract(NM_avg, axis = 0)
dSub

,95,97,99,101,103,105,107,109,111,113,...,871,873,875,877,879,881,883,885,887,889
0,0.004670,NaN,NaN,0.015237,0.044863,0.008642,0.034995,0.019582,-0.003553,0.022241,...,-0.003432,-0.015049,0.017872,0.028070,0.023401,0.057579,0.029958,-0.023564,0.036994,0.022949
1,0.065996,-0.033603,NaN,0.076037,0.087323,0.037242,0.117290,0.014422,0.051948,0.077343,...,-0.107562,0.040063,-0.030970,-0.161256,0.058945,0.094237,0.108443,-0.070108,0.082093,0.014830
2,0.590197,-0.008181,0.689951,0.222345,0.329270,0.283636,0.725274,0.260746,0.129485,0.280474,...,-0.057913,0.200371,0.459425,0.270391,0.478911,0.689230,0.466340,0.548906,0.655489,0.404186
3,-0.005893,0.003033,0.018468,0.009212,-0.005155,-0.001309,0.003503,-0.003278,-0.004997,-0.000168,...,0.009541,0.018119,0.027139,0.012237,0.000222,0.021634,0.005593,0.031740,0.036037,0.021235
4,-0.081763,0.049574,0.305408,0.373555,0.112867,-0.105240,0.048259,0.052108,-0.028440,0.122601,...,-0.161352,0.167339,0.176483,-0.003118,0.174851,0.409920,0.265441,0.396608,0.319946,0.063574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349415,-0.009434,-0.013613,0.000583,0.003172,0.014819,-0.001805,0.000316,0.008708,0.013652,0.020004,...,0.009844,-0.017558,0.008730,0.003816,-0.002923,0.002970,0.008287,0.009442,0.013887,0.010062
349416,-0.028009,-0.060788,-0.046198,-0.009732,-0.004002,0.008112,-0.053258,-0.011766,0.004360,0.007839,...,-0.020914,-0.015747,-0.005661,-0.018872,-0.041626,-0.043708,0.009904,0.002182,-0.014285,-0.058961
349417,-0.026395,-0.030290,NaN,NaN,-0.023315,-0.019325,-0.048044,0.007762,-0.000313,0.019738,...,-0.027083,0.052431,0.283946,0.046500,0.039126,0.228757,0.268548,0.133426,0.142187,0.017774
349418,0.018056,-0.012621,0.010067,0.052125,0.003590,0.037565,0.015946,0.002957,0.025103,0.006397,...,0.024445,0.045329,0.007076,0.001231,0.020450,0.036322,0.009183,0.026556,0.039537,-0.018085
349419,-0.049024,-0.096205,0.039321,0.030556,0.049327,0.046222,0.005803,0.081133,-0.029355,0.053871,...,0.041932,-0.111790,0.012305,0.049402,0.001289,0.030556,-0.005656,0.045064,0.068328,-0.015878

In [56]:
# Computing IQR
Q1 = dSub.T.quantile(0.25)
Q3 = dSub.T.quantile(0.75)
IQR = Q3 - Q1
upper_fence=Q3+IQR*1.5
lower_fence=Q1-IQR*1.5
print(upper_fence)
print(lower_fence)

0         0.075172
1         0.205111
2         0.979125
3         0.053971
4         0.657309
            ...
349415    0.036459
349416    0.059729
349417    0.266858
349418    0.051585
349419    0.157818
Length: 349420, dtype: float64
0        -0.040008
1        -0.140989
2        -0.353302
3        -0.027982
4        -0.399267
            ...
349415   -0.028653
349416   -0.084697
349417   -0.180672
349418   -0.044194
349419   -0.181546
Length: 349420, dtype: float64

In [62]:
dSub1=dSub.T
dSub_with_no_outlier = dSub1[(dSub1>lower_fence)&(dSub1<upper_fence)]
dSub_with_no_outlier.head(20)

,0,1,2,3,4,5,6,7,8,9,...,349410,349411,349412,349413,349414,349415,349416,349417,349418,349419
95,0.004670,0.065996,0.590197,-0.005893,-0.081763,-0.001122,-0.079697,-0.006011,0.005950,-0.028631,...,0.158281,0.017059,-0.030644,-0.034561,0.069673,-0.009434,-0.028009,-0.026395,0.018056,-0.049024
97,NaN,-0.033603,-0.008181,0.003033,0.049574,0.002278,0.150208,0.011360,-0.014403,0.032522,...,-0.136428,-0.003020,-0.040136,0.007361,-0.048760,-0.013613,-0.060788,-0.030290,-0.012621,-0.096205
99,NaN,NaN,0.689951,0.018468,0.305408,-0.003757,0.414896,-0.003007,0.003083,-0.038052,...,0.072553,0.020862,-0.034318,-0.031782,-0.156906,0.000583,-0.046198,NaN,0.010067,0.039321
101,0.015237,0.076037,0.222345,0.009212,0.373555,-0.003336,0.388926,0.002294,-0.007744,-0.015890,...,0.184931,0.007765,-0.009615,-0.011553,0.531563,0.003172,-0.009732,NaN,NaN,0.030556
103,0.044863,0.087323,0.329270,-0.005155,0.112867,-0.000998,0.227271,-0.021485,-0.004306,-0.031546,...,0.102277,0.001261,-0.023517,-0.029394,0.167761,0.014819,-0.004002,-0.023315,0.003590,0.049327
105,0.008642,0.037242,0.283636,-0.001309,-0.105240,0.000248,0.183453,-0.017491,-0.004568,0.069172,...,-0.081884,0.009962,0.034403,-0.020879,0.441898,-0.001805,0.008112,-0.019325,0.037565,0.046222
107,0.034995,0.117290,0.725274,0.003503,0.048259,-0.001926,0.081456,-0.002809,-0.002071,-0.020162,...,-0.080367,0.005411,-0.014975,0.001810,0.154975,0.000316,-0.053258,-0.048044,0.015946,0.005803
109,0.019582,0.014422,0.260746,-0.003278,0.052108,-0.002247,0.259461,0.002548,-0.010875,-0.013880,...,0.128570,0.009346,-0.014977,-0.013245,0.523605,0.008708,-0.011766,0.007762,0.002957,0.081133
111,-0.003553,0.051948,0.129485,-0.004997,-0.028440,-0.005028,0.224119,-0.005337,-0.010060,-0.019174,...,0.061096,-0.003620,-0.005875,-0.021147,0.483535,0.013652,0.004360,-0.000313,0.025103,-0.029355
113,0.022241,0.077343,0.280474,-0.000168,0.122601,-0.005219,0.185710,0.016983,-0.011172,0.064724,...,0.067629,0.003103,0.029806,NaN,0.457468,0.020004,0.007839,0.019738,0.006397,0.053871
115,0.011894,-0.106224,0.472603,0.019425,-0.286759,-0.006801,0.232652,-0.012273,-0.006310,-0.028349,...,0.108761,0.002814,-0.024426,0.017891,0.587711,0.008066,-0.010585,NaN,0.010296,0.042702
117,0.032027,0.023100,0.345713,0.000708,-0.179523,-0.003944,0.062159,-0.000277,0.005616,0.065124,...,0.069559,-0.008625,0.010541,-0.003461,0.265934,0.006329,-0.002855,0.117318,0.000099,0.059925
119,0.026268,0.033082,0.229413,0.000704,0.286593,-0.005319,0.059523,0.012596,0.015061,0.077769,...,0.126089,0.002935,0.004323,-0.019108,0.058022,0.005993,-0.009466,0.007177,-0.010431,0.013371
121,0.015821,0.085727,0.131820,0.012665,0.299539,-0.003489,0.223370,0.003251,-0.006835,0.039015,...,0.085253,-0.002338,-0.010174,0.004121,0.017707,0.018031,0.003176,-0.020518,0.004089,0.031187
123,0.031651,0.099063,0.000267,-0.004207,-0.111150,-0.002037,0.461988,-0.020338,-0.015804,-0.039194,...,0.135211,0.003000,0.046604,-0.031232,0.431002,0.002327,-0.031873,0.053624,0.034671,0.087397
125,0.036809,-0.019900,0.368850,0.015800,-0.123726,-0.006085,0.106192,-0.004309,-0.006914,-0.010154,...,0.076610,NaN,-0.034387,0.002507,0.508758,-0.007373,0.001395,-0.020000,0.027158,0.050897
127,NaN,0.058402,0.053490,0.002321,0.014137,-0.002155,0.162442,-0.019544,0.000277,-0.030018,...,0.144402,-0.004405,-0.017112,0.001045,0.003742,-0.005341,0.006108,0.072045,0.009441,0.064072
129,-0.031647,0.044406,0.280347,-0.000068,-0.005889,-0.006557,-0.080163,-0.014832,-0.000331,0.178443,...,0.085400,0.005210,0.002338,-0.006163,0.114248,-0.003860,-0.024738,-0.025427,-0.007182,-0.061476
131,0.040153,0.036668,0.322816,-0.006651,0.179063,0.000134,-0.135672,0.018302,-0.012976,0.099800,...,0.051145,-0.004298,NaN,-0.009178,0.523497,0.016581,0.005569,0.013295,0.021651,0.044787
133,0.007047,NaN,0.002934,0.022067,-0.022369,-0.000331,0.007487,-0.003490,0.001895,0.207802,...,0.091978,0.002779,0.004062,-0.005490,0.580707,0.005421,-0.038376,0.028981,NaN,-0.013038

In [121]:
dBeta=dSub_with_no_outlier.mean(skipna = True)
dBeta.head(20)

0     0.017616
1     0.032420
2     0.316867
3     0.014177
4     0.120412
5     0.000733
6     0.110206
7     0.001742
8    -0.000037
9     0.045484
10    0.194304
11   -0.002160
12    0.101679
13   -0.001815
14    0.020046
15    0.010520
16   -0.092154
17    0.010025
18    0.007572
19   -0.305178
dtype: float64

In [90]:
dBeta=abs(dBeta)
dBeta

0         0.017616
1         0.032420
2         0.316867
3         0.014177
4         0.120412
            ...
349415    0.003831
349416    0.013388
349417    0.038450
349418    0.003935
349419    0.011709
Length: 349420, dtype: float64

In [91]:
#dBeta=pd.DataFrame(dBeta, columns=['dBeta'])
#one=pd.DataFrame(dBeta, columns=['dBeta']).join(data)
one=pd.DataFrame(dBeta,columns=['dBeta']).join(df['ID'])
one

           dBeta          ID
0       0.017616  cg00000957
1       0.032420  cg00001349
2       0.316867  cg00001583
3       0.014177  cg00002028
4       0.120412  cg00002837
...          ...         ...
349415  0.003831  cg27656573
349416  0.013388  cg27657363
349417  0.038450  cg27657537
349418  0.003935  cg27662611
349419  0.011709  cg27665648

[349420 rows x 2 columns]

In [92]:
one.iloc[0:,1]

0         cg00000957
1         cg00001349
2         cg00001583
3         cg00002028
4         cg00002837
             ...
349415    cg27656573
349416    cg27657363
349417    cg27657537
349418    cg27662611
349419    cg27665648
Name: ID, Length: 349420, dtype: object

In [93]:
DMP=pd.read_csv('C:/Users/Administrator/Documents/DMP_result_TN.csv')
DMP.rename(columns={'Unnamed: 0': 'ID'}, inplace=True)
DMP_merge=pd.DataFrame(DMP['ID']).join(DMP['gene'])
DMP_merge

                ID     gene
0       cg05434287   MAD1L1
1       cg14789818      NaN
2       cg20699586      NaN
3       cg24974704    ZC3H3
4       cg27616751     FIS1
...            ...      ...
268107  cg10175910   DENND3
268108  cg21782712    WDR46
268109  cg18997124  C6orf27
268110  cg11439068     PAK4
268111  cg11590213    MAST4

[268112 rows x 2 columns]

In [94]:
#找ID交集
dBeta_TN=pd.merge(one.iloc[0:,1],DMP_merge,how='inner')
pd.DataFrame(dBeta_TN)
dBeta_TN=dBeta_TN.dropna()
dBeta_TN

                ID      gene
0       cg00001583     NR5A2
1       cg00002028     PINK1
3       cg00003287     TNNT2
4       cg00007036    ZNF362
5       cg00008647     FAIM3
...            ...       ...
268104  cg27612019  SLC25A18
268105  cg27614432      SELM
268106  cg27634744    CELSR1
268109  cg27657537     MED15
268110  cg27662611      MAFF

[206165 rows x 2 columns]

In [95]:
dBeta_TN1=pd.merge(dBeta_TN,one,how='inner')
dBeta_TN1

                ID      gene     dBeta
0       cg00001583     NR5A2  0.316867
1       cg00002028     PINK1  0.014177
2       cg00003287     TNNT2  0.110206
3       cg00007036    ZNF362  0.001742
4       cg00008647     FAIM3  0.045484
...            ...       ...       ...
206160  cg27612019  SLC25A18  0.090578
206161  cg27614432      SELM  0.007436
206162  cg27634744    CELSR1  0.005338
206163  cg27657537     MED15  0.038450
206164  cg27662611      MAFF  0.003935

[206165 rows x 3 columns]

In [96]:
GeneSame=dBeta_TN1[dBeta_TN1.duplicated(subset='gene',keep=False)]
GeneSame=GeneSame.sort_values(['gene','dBeta'])
GeneSame

                ID   gene     dBeta
58619   cg22286978   A1BG  0.001372
56641   cg10734734   A1BG  0.004265
194297  cg14222245   A1BG  0.185701
55584   cg03630821   A1BG  0.330774
175993  cg07115206  A2BP1  0.032787
...            ...    ...       ...
551     cg02490994   ZZZ3  0.002103
4036    cg17224732   ZZZ3  0.002260
66345   cg04127303   ZZZ3  0.002842
66901   cg05029193   ZZZ3  0.003585
78387   cg26534213   ZZZ3  0.006052

[205137 rows x 3 columns]

In [97]:
GeneSame=GeneSame.drop_duplicates(subset='gene', keep='last')
GeneSame

                ID    gene     dBeta
55584   cg03630821    A1BG  0.330774
175823  cg06719334   A2BP1  0.436338
162261  cg13776095   A2LD1  0.269246
153411  cg00134295     A2M  0.207143
157584  cg15769388   A2ML1  0.143162
...            ...     ...       ...
68940   cg08736216  ZYG11A  0.063697
3977    cg17101920  ZYG11B  0.011458
122171  cg09704136     ZYX  0.236211
53821   cg26591066   ZZEF1  0.297844
78387   cg26534213    ZZZ3  0.006052

[17337 rows x 3 columns]

In [110]:
dBeta_TN1=dBeta_TN1.drop_duplicates(subset='gene',keep=False)
dBeta_TN1

                ID      gene     dBeta
1044    cg04705907  C1orf112  0.005193
1351    cg05943574     OR2G6  0.295672
1582    cg06893172   HORMAD1  0.007101
1966    cg08471734    CELA2B  0.001456
2633    cg11404129      ECM1  0.020854
...            ...       ...       ...
205754  cg22664428    DGCR11  0.004015
205905  cg24714094      GNAZ  0.077297
205912  cg24846343      DDTL  0.090522
205975  cg25559898  MIRLET7B  0.085544
206068  cg26654001     RNU12  0.003219

[1028 rows x 3 columns]

In [111]:
dBeta_TN=dBeta_TN1.append(GeneSame)
dBeta_TN

                ID      gene     dBeta
1044    cg04705907  C1orf112  0.005193
1351    cg05943574     OR2G6  0.295672
1582    cg06893172   HORMAD1  0.007101
1966    cg08471734    CELA2B  0.001456
2633    cg11404129      ECM1  0.020854
...            ...       ...       ...
68940   cg08736216    ZYG11A  0.063697
3977    cg17101920    ZYG11B  0.011458
122171  cg09704136       ZYX  0.236211
53821   cg26591066     ZZEF1  0.297844
78387   cg26534213      ZZZ3  0.006052

[18365 rows x 3 columns]

In [112]:
dBeta_DMP_TN=pd.merge(dBeta_TN,DMP,how='inner')
dBeta_DMP_TN

,ID,gene,dBeta,logFC,AveExpr,t,P.Value,adj.P.Val,B,Normal_AVG,...,Type,feature,cgi,feat.cgi,UCSC_CpG_Islands_Name,DHS,Enhancer,Phantom,Probe_SNPs,Probe_SNPs_10
0,cg04705907,C1orf112,0.005193,0.007357,0.039544,2.106932,3.540301e-02,4.639217e-02,-5.595848,0.032965,...,I,TSS1500,island,TSS1500-island,chr1:169763973-169764347,NaN,NaN,high-CpG:168030798-168030825,rs76554462,NaN
1,cg05943574,OR2G6,0.295672,-0.284772,0.560310,-13.057701,8.907328e-36,1.702998e-34,70.133629,0.815005,...,I,1stExon,opensea,1stExon-opensea,NaN,NaN,NaN,NaN,NaN,NaN
2,cg06893172,HORMAD1,0.007101,-0.033246,0.900467,-2.334470,1.979293e-02,2.695357e-02,-5.093601,0.930202,...,I,TSS200,opensea,TSS200-opensea,NaN,NaN,NaN,NaN,rs80244686,NaN
3,cg08471734,CELA2B,0.001456,0.005348,0.967688,3.493525,5.002023e-04,8.580257e-04,-1.751007,0.962905,...,I,Body,opensea,Body-opensea,NaN,NaN,NaN,NaN,NaN,NaN
4,cg11404129,ECM1,0.020854,-0.028439,0.871391,-4.343793,1.561719e-05,3.259599e-05,1.521991,0.896826,...,I,Body,shelf,Body-shelf,chr1:150488036-150488416,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18360,cg08736216,ZYG11A,0.063697,-0.058260,0.581653,-3.363818,8.015823e-04,1.336474e-03,-2.189700,0.633759,...,II,TSS200,shore,TSS200-shore,chr1:53308294-53309262,NaN,NaN,NaN,NaN,NaN
18361,cg17101920,ZYG11B,0.011458,0.007325,0.087089,2.785454,5.458948e-03,8.086285e-03,-3.948192,0.080538,...,I,Body,island,Body-island,chr1:53192023-53192428,NaN,NaN,NaN,NaN,NaN
18362,cg09704136,ZYX,0.236211,0.222840,0.739851,17.463163,6.098736e-59,4.319052e-57,123.194378,0.540547,...,II,Body,shelf,Body-shelf,chr7:143077469-143079169,NaN,True,NaN,NaN,NaN
18363,cg26591066,ZZEF1,0.297844,0.262805,0.802987,18.676116,6.356968e-66,6.538863e-64,139.204855,0.567938,...,I,Body,opensea,Body-opensea,NaN,NaN,NaN,NaN,NaN,NaN
18364,cg26534213,ZZZ3,0.006052,0.006545,0.055385,2.742580,6.218397e-03,9.136150e-03,-4.065627,0.049532,...,II,TSS1500,shore,TSS1500-shore,chr1:78148217-78149418,NaN,NaN,high-CpG:77921580-77922170,NaN,NaN

In [113]:
dBeta_DMP_TN[dBeta_DMP_TN['dBeta']>0.4]

,ID,gene,dBeta,logFC,AveExpr,t,P.Value,adj.P.Val,B,Normal_AVG,...,Type,feature,cgi,feat.cgi,UCSC_CpG_Islands_Name,DHS,Enhancer,Phantom,Probe_SNPs,Probe_SNPs_10
1029,cg06719334,A2BP1,0.436338,-0.428592,0.472278,-19.996857,9.465509e-74,1.461528e-71,157.158587,0.855603,...,II,Body,opensea,Body-opensea,NaN,NaN,True,NaN,NaN,NaN
1151,cg24613080,ACCN1,0.406314,0.362457,0.479594,20.416543,2.792829e-76,4.872043e-74,162.963043,0.155419,...,I,TSS1500,island,TSS1500-island,chr17:32484007-32484280,NaN,True,NaN,NaN,NaN
1169,cg10266490,ACOT11,0.403402,0.367619,0.598829,23.875495,9.670088e-98,5.096413e-95,212.209112,0.270037,...,II,TSS200,opensea,TSS200-opensea,NaN,NaN,NaN,NaN,NaN,NaN
1211,cg24471254,ACTL6B,0.456693,0.410154,0.696026,21.608618,1.451286e-83,3.709643e-81,179.676383,0.329192,...,I,Body,island,Body-island,chr7:100253782-100254150,True,NaN,NaN,NaN,rs2231169
1267,cg26573704,ADAMTS12,0.408026,0.389620,0.415211,13.173306,2.482214e-36,4.903800e-35,71.403041,0.066741,...,II,TSS200,island,TSS200-island,chr5:33892191-33892403,True,NaN,high-CpG:33927847-33928066,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18098,cg03975694,ZNF540,0.415926,0.398355,0.523561,21.299531,1.157285e-81,2.670929e-79,175.312827,0.167279,...,II,5'UTR,shelf,5'UTR-shelf,chr19:38039561-38040395,NaN,NaN,NaN,NaN,NaN
18116,cg05221167,ZNF560,0.413683,0.407099,0.493785,20.805673,1.211934e-78,2.421234e-76,168.383495,0.129684,...,II,TSS200,shore,TSS200-shore,chr19:9608804-9609343,NaN,NaN,NaN,NaN,NaN
18186,cg22598028,ZNF660,0.402876,0.395178,0.399837,14.538057,4.056915e-43,1.180617e-41,86.936664,0.046397,...,II,5'UTR,island,5'UTR-island,chr3:44626325-44626794,True,NaN,NaN,NaN,NaN
18222,cg22637867,ZNF709,0.422569,0.411243,0.657164,27.363753,4.377503e-120,7.844037e-117,263.493668,0.289356,...,II,5'UTR,island,5'UTR-island,chr19:12624273-12624477,NaN,NaN,NaN,NaN,rs35376025
18338,cg14231297,ZSCAN18,0.401591,0.393594,0.525545,31.363669,5.426081e-146,3.577323e-142,322.954245,0.173521,...,I,TSS200,island,TSS200-island,chr19:58629309-58630241,NaN,NaN,NaN,rs8109359,NaN

In [114]:
#Result
outputpath='C:/Users/Administrator/Documents/dBeta_TN.csv'
dBeta_TN.to_csv(outputpath,sep=',',index=False,header=True)

In [78]:
#dBeta
outputpath='C:/Users/Administrator/Documents/dBeta.csv'
one.to_csv(outputpath,sep=',',index=False,header=True,columns=['ID', 'dBeta'])

In [ ]:
#data
outputpath='C:/Users/Administrator/Documents/Data.csv'
data.iloc[349419,0:].to_csv(outputpath,sep=',',index=False,header=True)