In [1]:
import pandas as pd

### Parameter

In [2]:
comorbidity = 'group'

### Settings

In [3]:
source_path = f'../result/all_beta_normalized_result_test_{comorbidity}.csv'
method_list = ['J','CZ','ER','UI','F1']

In [4]:
test_df = pd.read_csv(source_path)
print(test_df.shape)
test_df.head()

(85584, 28)

,ID,gene,t_dbeta_avg,"J,J","J,CZ","J,ER","J,UI","J,F1","CZ,J","CZ,CZ",...,"UI,J","UI,CZ","UI,ER","UI,UI","UI,F1","F1,J","F1,CZ","F1,ER","F1,UI","F1,F1"
0,cg08296903,ERCC4,0.227467,0.815013,0.815013,0.815013,0.865952,0.815013,0.815013,0.815013,...,0.184987,0.184987,0.184987,0.230885,0.184987,0.898080,0.898080,0.898080,0.928161,0.898080
1,cg17046586,LIMA1,0.351587,0.893617,0.893617,0.893617,0.914894,0.893617,0.893617,0.893617,...,0.106383,0.106383,0.106383,0.085106,0.106383,0.943820,0.943820,0.943820,0.955556,0.943820
2,cg25198340,IL17RD,0.281724,0.775510,0.775510,0.857143,0.897959,0.775510,0.775510,0.775510,...,0.224490,0.224490,0.186652,0.227468,0.224490,0.873563,0.873563,0.923077,0.946237,0.873563
3,cg19366479,NR1H2,0.367468,0.740000,0.740000,0.740000,0.920000,0.740000,0.740000,0.740000,...,0.260000,0.260000,0.260000,0.080000,0.260000,0.850575,0.850575,0.850575,0.958333,0.850575
4,cg19130973,IQSEC1,0.361450,0.984085,0.984085,0.978723,0.914894,0.984085,0.984085,0.984085,...,0.197415,0.197415,0.192054,0.128224,0.197415,0.991979,0.991979,0.989247,0.955556,0.991979

In [5]:
test_df.columns

Index(['ID', 'gene', 't_dbeta_avg', 'J,J', 'J,CZ', 'J,ER', 'J,UI', 'J,F1',
       'CZ,J', 'CZ,CZ', 'CZ,ER', 'CZ,UI', 'CZ,F1', 'ER,J', 'ER,CZ', 'ER,ER',
       'ER,UI', 'ER,F1', 'UI,J', 'UI,CZ', 'UI,ER', 'UI,UI', 'UI,F1', 'F1,J',
       'F1,CZ', 'F1,ER', 'F1,UI', 'F1,F1'],
      dtype='object')

In [6]:
for i in method_list:
    ascending = False
    if i == 'ER' or i == 'UI':
        ascending = True
    for j in method_list:    
        test_df[f'{i},{j}_rank'] = test_df[f'{i},{j}'].rank(ascending=ascending)

In [13]:
DMP_result = pd.read_csv('../champ_result/DMP_result.csv')
DMP_result.rename(columns={'Unnamed: 0':'ID'}, inplace=True)
DMP = DMP_result.drop(DMP_result.columns[1:10], axis=1)
DMP = DMP.drop('gene', axis=1)
DMP.head()

,ID,CHR,MAPINFO,Strand,Type,feature,cgi,feat.cgi,UCSC_CpG_Islands_Name,DHS,Enhancer,Phantom,Probe_SNPs,Probe_SNPs_10
0,cg05434287,7,2030229,F,I,Body,shore,Body-shore,chr7:2029116-2029326,NaN,NaN,NaN,rs78394594,NaN
1,cg14789818,1,227748712,R,I,IGR,island,IGR-island,chr1:227748423-227748860,NaN,NaN,NaN,NaN,NaN
2,cg20699586,1,227748719,R,I,IGR,island,IGR-island,chr1:227748423-227748860,NaN,NaN,NaN,NaN,NaN
3,cg24974704,8,144577238,F,I,Body,opensea,Body-opensea,NaN,True,NaN,NaN,NaN,NaN
4,cg27616751,7,100883077,F,I,3'UTR,opensea,3'UTR-opensea,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
test_df = pd.merge(test_df, DMP, on='ID')
test_df.head()

,ID,gene,t_dbeta_avg,"J,J","J,CZ","J,ER","J,UI","J,F1","CZ,J","CZ,CZ",...,Type,feature,cgi,feat.cgi,UCSC_CpG_Islands_Name,DHS,Enhancer,Phantom,Probe_SNPs,Probe_SNPs_10
0,cg08296903,ERCC4,0.227467,0.815013,0.815013,0.815013,0.865952,0.815013,0.815013,0.815013,...,II,Body,opensea,Body-opensea,NaN,NaN,NaN,NaN,rs55736359,NaN
1,cg17046586,LIMA1,0.351587,0.893617,0.893617,0.893617,0.914894,0.893617,0.893617,0.893617,...,II,5'UTR,opensea,5'UTR-opensea,NaN,NaN,True,NaN,NaN,NaN
2,cg25198340,IL17RD,0.281724,0.775510,0.775510,0.857143,0.897959,0.775510,0.775510,0.775510,...,II,Body,opensea,Body-opensea,NaN,NaN,True,NaN,rs17235834,NaN
3,cg19366479,NR1H2,0.367468,0.740000,0.740000,0.740000,0.920000,0.740000,0.740000,0.740000,...,II,Body,shore,Body-shore,chr19:50885178-50885490,NaN,NaN,NaN,NaN,NaN
4,cg19130973,IQSEC1,0.361450,0.984085,0.984085,0.978723,0.914894,0.984085,0.984085,0.984085,...,II,Body,shore,Body-shore,chr3:12976966-12978182,True,True,NaN,NaN,NaN

In [9]:
test_df.to_csv(f'../result/all_beta_normalized_result_test_{comorbidity}_rank.csv', index=False)