#### 450K 組織計算hyper/hypo

In [3]:
import pandas as pd
df_filter =pd.read_csv('../../資料整理/3_train_dbeta_0.35.csv')
df_filter

             ID     dbeta     gene
0    cg13670057  0.359170     ABL1
1    cg10266490  0.403402   ACOT11
2    cg10976772  0.365513    ACOT7
3    cg18770350  0.375086    ACTN2
4    cg09499849  0.383661    ACVR1
..          ...       ...      ...
383  cg04738965  0.408686     ZIC1
384  cg16768018  0.462100     ZIC4
385  cg20985450  0.402938     ZIC5
386  cg21183523  0.381336   ZNF521
387  cg14231297  0.401591  ZSCAN18

[388 rows x 3 columns]

In [4]:
train=pd.read_csv('../../all_beta_normalized_train.csv')

In [7]:
df_gene = train[train['Unnamed: 0'].isin(df_filter['ID'])]
df_gene.reset_index(drop=True, inplace=True)
print(df_gene.shape)
df_gene.head()

(388, 891)

,Unnamed: 0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
0,cg03520644,0.229817,0.229817,0.079642,0.079642,0.180363,0.180363,0.182330,0.182330,0.156993,...,0.787966,0.787966,0.717043,0.717043,0.732963,0.732963,0.653539,0.653539,0.324511,0.324511
1,cg05047401,0.291908,0.291908,0.030616,0.030616,0.219142,0.219142,0.228138,0.228138,0.164601,...,0.790363,0.790363,0.774816,0.774816,0.738141,0.738141,0.780185,0.780185,0.721786,0.721786
2,cg06355129,0.232184,0.232184,0.261523,0.261523,0.176360,0.176360,0.253273,0.253273,0.083640,...,0.913858,0.913858,0.757479,0.757479,0.796541,0.796541,0.798998,0.798998,0.744522,0.744522
3,cg07790615,0.029336,0.029336,0.031738,0.031738,0.052790,0.052790,0.075713,0.075713,0.052144,...,0.793958,0.793958,0.713349,0.713349,0.809180,0.809180,0.798897,0.798897,0.584788,0.584788
4,cg09106903,0.091505,0.091505,0.066134,0.066134,0.126135,0.126135,0.094016,0.094016,0.039025,...,0.726509,0.726509,0.795497,0.795497,0.632736,0.632736,0.779592,0.779592,0.643527,0.643527

In [8]:
train_normal = df_gene.iloc[:,1:94:2]
train_tumor = df_gene.iloc[:,94::2]

train_tumor.columns=range(0,train_tumor.shape[1])
train_normal.columns=range(0,train_normal.shape[1])

train_tumor = train_tumor.T
train_normal = train_normal.T

In [9]:
train_normal_avg = train_normal.mean(skipna=True, axis=0)
tt_dbeta=(train_tumor).subtract(train_normal_avg, axis = 1)

In [10]:
tt_dbeta #tumor delta beta

,0,1,2,3,4,5,6,7,8,9,...,378,379,380,381,382,383,384,385,386,387
0,0.002722,0.159005,-0.074853,-0.017650,-0.020078,-0.040330,0.120806,-0.020801,-0.049774,0.090429,...,-0.100359,0.024904,0.023625,-0.026049,0.120544,-0.149759,-0.011675,0.022688,-0.086617,-0.010292
1,0.389678,0.465189,0.542915,0.286332,-0.042442,-0.033815,0.248216,0.134212,0.716888,0.309457,...,-0.001722,-0.472042,0.068169,0.458086,0.540094,-0.085528,0.575783,0.470906,0.100288,0.094093
2,0.252075,0.175216,-0.123224,0.291589,0.057750,-0.036066,-0.021861,0.018924,0.312647,0.414744,...,-0.429717,-0.406133,-0.027593,0.301364,-0.114673,-0.356939,0.169272,0.365579,0.451684,0.314283
3,0.476008,0.537575,0.568644,0.669520,0.572042,0.699485,0.581460,0.567749,0.719191,0.659896,...,-0.658007,-0.687373,0.631484,0.639570,0.619501,-0.260103,0.606957,0.627974,0.696148,0.746992
4,0.588893,0.524286,0.565482,0.658430,0.426472,0.630411,0.565579,0.700177,0.783661,0.623989,...,-0.546276,-0.697865,0.451131,0.602240,0.611190,-0.615514,0.669343,0.567665,0.676229,0.728267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,0.572551,0.520178,0.703143,0.725358,0.599171,0.685983,0.636285,0.675907,0.786011,0.649860,...,-0.189605,-0.550418,0.593598,0.614020,0.580360,-0.358228,0.651529,0.472912,0.731291,0.592605
395,0.501627,0.504631,0.546765,0.644750,0.668159,0.558093,0.616556,0.578003,0.740482,0.618489,...,-0.353336,-0.475268,0.449139,0.135412,0.553494,-0.256033,0.515776,0.560417,0.520019,0.321048
396,0.517547,0.467956,0.585826,0.740581,0.505398,0.652302,0.614133,0.734720,0.703586,0.475552,...,-0.549868,-0.531522,0.548960,0.503054,0.560129,-0.557767,0.617468,0.543598,0.640912,0.042638
397,0.438123,0.510000,0.588283,0.730298,0.652255,0.702540,0.594839,0.761389,0.759065,0.602627,...,-0.550420,-0.418239,0.630213,0.621442,0.581819,-0.521292,0.648855,0.544397,0.631176,0.667682
398,0.109095,0.451602,0.533807,0.516189,0.516189,0.513884,0.378469,0.028979,0.563690,0.522391,...,-0.449940,-0.444048,0.347016,0.406864,0.374154,-0.573933,0.338432,0.337987,0.252849,0.252383

標註Hyper/Hypo

In [13]:
avg_tumordBeta = tt_dbeta.mean(axis=0) #avg( Δβ (tumor) ) 
avg_tumordBeta

0      0.348612
1      0.401801
2      0.374405
3      0.449935
4      0.349763
         ...
383   -0.381687
384    0.346137
385    0.369598
386    0.361652
387    0.344138
Length: 388, dtype: float64

In [19]:
methylation_level_df = pd.DataFrame({'ID': df_gene['Unnamed: 0'], 'methylation_level': avg_tumordBeta.apply(lambda x: 'Hyper' if x > 0 else 'Hypo')})
methylation_level_df

             ID methylation_level
0    cg03520644             Hyper
1    cg05047401             Hyper
2    cg06355129             Hyper
3    cg07790615             Hyper
4    cg09106903             Hyper
..          ...               ...
383  cg15242225              Hypo
384  cg19678828             Hyper
385  cg00058879             Hyper
386  cg07879739             Hyper
387  cg20486569             Hyper

[388 rows x 2 columns]

In [20]:
cp_data=pd.read_csv('../result/result_basic_dbeta_0.35.csv')
cp_data.rename(columns={'Unnamed: 0': 'ID'}, inplace=True)
cp_data

,ID,dbeta,gene,"J,J","J,CZ","J,ER","J,F1","CZ,J","CZ,CZ","CZ,ER",...,Type,feature,cgi,feat.cgi,UCSC_CpG_Islands_Name,DHS,Enhancer,Phantom,Probe_SNPs,Probe_SNPs_10
0,cg13670057,0.359170,ABL1,0.8400,0.8400,0.8525,0.8400,0.84600,0.84600,0.85775,...,II,Body,opensea,Body-opensea,NaN,NaN,True,NaN,NaN,NaN
1,cg10266490,0.403402,ACOT11,0.6750,0.6750,0.6750,0.6750,0.70090,0.70090,0.70090,...,II,TSS200,opensea,TSS200-opensea,NaN,NaN,NaN,NaN,NaN,NaN
2,cg10976772,0.365513,ACOT7,0.7025,0.7025,0.6750,0.7025,0.72365,0.72365,0.69810,...,II,Body,opensea,Body-opensea,NaN,True,True,NaN,NaN,NaN
3,cg18770350,0.375086,ACTN2,0.7600,0.7600,0.7050,0.7600,0.77400,0.77400,0.72570,...,I,1stExon,island,1stExon-island,chr1:236849472-236850323,True,True,high-CpG:234916417-234916759,NaN,NaN
4,cg09499849,0.383661,ACVR1,0.6875,0.6875,0.6875,0.6875,0.71060,0.71060,0.71060,...,II,5'UTR,opensea,5'UTR-opensea,NaN,NaN,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,cg04738965,0.408686,ZIC1,0.7925,0.7925,0.8025,0.7925,0.79625,0.79625,0.80880,...,I,1stExon,island,1stExon-island,chr3:147126988-147128999,True,True,NaN,NaN,NaN
384,cg16768018,0.462100,ZIC4,0.7375,0.7375,0.7475,0.7375,0.74965,0.74965,0.75905,...,I,Body,island,Body-island,chr3:147108511-147111703,NaN,NaN,NaN,NaN,NaN
385,cg20985450,0.402938,ZIC5,0.7725,0.7725,0.6675,0.6675,0.78540,0.78540,0.68970,...,I,Body,island,Body-island,chr13:100620241-100624348,NaN,NaN,NaN,NaN,rs61080730
386,cg21183523,0.381336,ZNF521,0.6225,0.6225,0.4425,0.6225,0.64630,0.64630,0.50995,...,II,Body,shore,Body-shore,chr18:22930018-22930904,NaN,NaN,NaN,NaN,NaN
387,cg14231297,0.401591,ZSCAN18,0.6925,0.6925,0.6275,0.6925,0.70320,0.70320,0.66005,...,I,TSS200,island,TSS200-island,chr19:58629309-58630241,NaN,NaN,NaN,rs8109359,NaN

In [21]:
merged_df = pd.merge(cp_data, methylation_level_df, on='ID', how='inner')
merged_df

,ID,dbeta,gene,"J,J","J,CZ","J,ER","J,F1","CZ,J","CZ,CZ","CZ,ER",...,feature,cgi,feat.cgi,UCSC_CpG_Islands_Name,DHS,Enhancer,Phantom,Probe_SNPs,Probe_SNPs_10,methylation_level
0,cg13670057,0.359170,ABL1,0.8400,0.8400,0.8525,0.8400,0.84600,0.84600,0.85775,...,Body,opensea,Body-opensea,NaN,NaN,True,NaN,NaN,NaN,Hyper
1,cg10266490,0.403402,ACOT11,0.6750,0.6750,0.6750,0.6750,0.70090,0.70090,0.70090,...,TSS200,opensea,TSS200-opensea,NaN,NaN,NaN,NaN,NaN,NaN,Hyper
2,cg10976772,0.365513,ACOT7,0.7025,0.7025,0.6750,0.7025,0.72365,0.72365,0.69810,...,Body,opensea,Body-opensea,NaN,True,True,NaN,NaN,NaN,Hyper
3,cg18770350,0.375086,ACTN2,0.7600,0.7600,0.7050,0.7600,0.77400,0.77400,0.72570,...,1stExon,island,1stExon-island,chr1:236849472-236850323,True,True,high-CpG:234916417-234916759,NaN,NaN,Hyper
4,cg09499849,0.383661,ACVR1,0.6875,0.6875,0.6875,0.6875,0.71060,0.71060,0.71060,...,5'UTR,opensea,5'UTR-opensea,NaN,NaN,True,NaN,NaN,NaN,Hyper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,cg04738965,0.408686,ZIC1,0.7925,0.7925,0.8025,0.7925,0.79625,0.79625,0.80880,...,1stExon,island,1stExon-island,chr3:147126988-147128999,True,True,NaN,NaN,NaN,Hyper
384,cg16768018,0.462100,ZIC4,0.7375,0.7375,0.7475,0.7375,0.74965,0.74965,0.75905,...,Body,island,Body-island,chr3:147108511-147111703,NaN,NaN,NaN,NaN,NaN,Hyper
385,cg20985450,0.402938,ZIC5,0.7725,0.7725,0.6675,0.6675,0.78540,0.78540,0.68970,...,Body,island,Body-island,chr13:100620241-100624348,NaN,NaN,NaN,NaN,rs61080730,Hyper
386,cg21183523,0.381336,ZNF521,0.6225,0.6225,0.4425,0.6225,0.64630,0.64630,0.50995,...,Body,shore,Body-shore,chr18:22930018-22930904,NaN,NaN,NaN,NaN,NaN,Hyper
387,cg14231297,0.401591,ZSCAN18,0.6925,0.6925,0.6275,0.6925,0.70320,0.70320,0.66005,...,TSS200,island,TSS200-island,chr19:58629309-58630241,NaN,NaN,NaN,rs8109359,NaN,Hyper

計算Up/Down regulation(使用F1 cutpoint為基準)

In [22]:
cp=pd.read_csv("../../資料整理/1_388gene_cutpoint.csv")
cp

,J,J cut-point,J sensitivity,J specificity,CZ,CZ cut-point,CZ sensitivity,CZ specificity,ER,ER cut-point,ER sensitivity,ER specificity,F1,F1 cut-point,F1 sensitivity,F1 specificity,AUC
0,0.872180,0.16,0.997494,0.106383,0.872180,0.16,0.997494,0.106383,0.124636,0.15,0.997494,0.106383,0.931727,0.16,0.997494,0.106383,0.854743
1,0.893510,0.25,1.000000,0.063830,0.895323,0.25,1.000000,0.063830,0.087829,0.25,1.000000,0.063830,0.945676,0.25,1.000000,0.063830,0.915827
2,0.840879,0.12,0.984962,0.106383,0.843812,0.12,0.984962,0.106383,0.131504,0.10,0.984962,0.106383,0.916749,0.12,0.984962,0.106383,0.838026
3,0.854637,0.12,0.979950,0.212766,0.854637,0.12,0.979950,0.212766,0.143299,0.06,0.979950,0.212766,0.921622,0.12,0.979950,0.212766,0.737135
4,0.764464,0.11,0.977444,0.106383,0.772676,0.11,0.977444,0.106383,0.197618,0.11,0.977444,0.106383,0.875820,0.11,0.977444,0.106383,0.793393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,0.819549,0.20,0.994987,0.042553,0.819549,0.20,0.994987,0.042553,0.161058,0.17,0.994987,0.042553,0.900826,0.20,0.994987,0.042553,0.890071
384,0.798272,0.14,0.982456,0.127660,0.802112,0.14,0.982456,0.127660,0.180526,0.13,0.982456,0.127660,0.892091,0.14,0.982456,0.127660,0.800005
385,0.869674,0.19,0.992481,0.127660,0.869674,0.19,0.992481,0.127660,0.114771,0.17,0.992481,0.127660,0.930727,0.17,0.992481,0.127660,0.826214
386,0.682984,0.22,0.972431,0.021277,0.689276,0.22,0.972431,0.021277,0.266849,0.11,0.972431,0.021277,0.819112,0.22,0.972431,0.021277,0.835200
387,0.668000,0.14,0.967419,0.106383,0.685117,0.14,0.967419,0.106383,0.267954,0.10,0.967419,0.106383,0.821483,0.14,0.967419,0.106383,0.769130

In [25]:
import numpy as np
cut_point = cp["F1 cut-point"]

regulation = pd.DataFrame({
    'ID': df_gene['Unnamed: 0'],
    'regulation': np.where(avg_tumordBeta > cut_point, 'Up', 'Down')
})
regulation

             ID regulation
0    cg03520644         Up
1    cg05047401         Up
2    cg06355129         Up
3    cg07790615         Up
4    cg09106903         Up
..          ...        ...
383  cg15242225       Down
384  cg19678828         Up
385  cg00058879         Up
386  cg07879739         Up
387  cg20486569         Up

[388 rows x 2 columns]

In [26]:
merged_df=pd.merge(merged_df, regulation, on='ID', how='inner')
merged_df

,ID,dbeta,gene,"J,J","J,CZ","J,ER","J,F1","CZ,J","CZ,CZ","CZ,ER",...,cgi,feat.cgi,UCSC_CpG_Islands_Name,DHS,Enhancer,Phantom,Probe_SNPs,Probe_SNPs_10,methylation_level,regulation
0,cg13670057,0.359170,ABL1,0.8400,0.8400,0.8525,0.8400,0.84600,0.84600,0.85775,...,opensea,Body-opensea,NaN,NaN,True,NaN,NaN,NaN,Hyper,Up
1,cg10266490,0.403402,ACOT11,0.6750,0.6750,0.6750,0.6750,0.70090,0.70090,0.70090,...,opensea,TSS200-opensea,NaN,NaN,NaN,NaN,NaN,NaN,Hyper,Up
2,cg10976772,0.365513,ACOT7,0.7025,0.7025,0.6750,0.7025,0.72365,0.72365,0.69810,...,opensea,Body-opensea,NaN,True,True,NaN,NaN,NaN,Hyper,Up
3,cg18770350,0.375086,ACTN2,0.7600,0.7600,0.7050,0.7600,0.77400,0.77400,0.72570,...,island,1stExon-island,chr1:236849472-236850323,True,True,high-CpG:234916417-234916759,NaN,NaN,Hyper,Up
4,cg09499849,0.383661,ACVR1,0.6875,0.6875,0.6875,0.6875,0.71060,0.71060,0.71060,...,opensea,5'UTR-opensea,NaN,NaN,True,NaN,NaN,NaN,Hyper,Up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,cg04738965,0.408686,ZIC1,0.7925,0.7925,0.8025,0.7925,0.79625,0.79625,0.80880,...,island,1stExon-island,chr3:147126988-147128999,True,True,NaN,NaN,NaN,Hyper,Up
384,cg16768018,0.462100,ZIC4,0.7375,0.7375,0.7475,0.7375,0.74965,0.74965,0.75905,...,island,Body-island,chr3:147108511-147111703,NaN,NaN,NaN,NaN,NaN,Hyper,Up
385,cg20985450,0.402938,ZIC5,0.7725,0.7725,0.6675,0.6675,0.78540,0.78540,0.68970,...,island,Body-island,chr13:100620241-100624348,NaN,NaN,NaN,NaN,rs61080730,Hyper,Up
386,cg21183523,0.381336,ZNF521,0.6225,0.6225,0.4425,0.6225,0.64630,0.64630,0.50995,...,shore,Body-shore,chr18:22930018-22930904,NaN,NaN,NaN,NaN,NaN,Hyper,Up
387,cg14231297,0.401591,ZSCAN18,0.6925,0.6925,0.6275,0.6925,0.70320,0.70320,0.66005,...,island,TSS200-island,chr19:58629309-58630241,NaN,NaN,NaN,rs8109359,NaN,Hyper,Up

In [ ]:
merged_df.to_csv("../result/result_regulation_dbeta_0.35.csv",index=False)

#### GSE89093 液態計算hyper/hypo

In [2]:
#GSE89093(46Normal/46Tumor)
import pandas as pd
gene_dbeta=pd.read_csv("../result/result_basic_dbeta_GSE89093.csv")
gene_dbeta=gene_dbeta[((abs(gene_dbeta['dbeta'])>0.52)&((gene_dbeta['UCSC_RefGene_Group']=='TSS1500')|(gene_dbeta['UCSC_RefGene_Group']=='TSS200')))]
# gene_dbeta.to_csv("liquid_GSE89093_dBeta_0.52.csv",index=False)
gene_dbeta

              ID     dbeta UCSC_RefGene_Name UCSC_RefGene_Group
8     cg06971602 -0.521134              AATF             TSS200
55    cg05886574 -0.520869             ACBD5            TSS1500
89    cg10739033 -0.520998            ACTR10            TSS1500
92    cg15517836 -0.521456             ACTR3             TSS200
105   cg06253734 -0.520567            ADAM10             TSS200
...          ...       ...               ...                ...
7959  cg03642224 -0.520487            YME1L1             TSS200
7969  cg27417922 -0.521182             YWHAG             TSS200
7991  cg12600418 -0.520579           ZC3H12A             TSS200
8018  cg21861211 -0.521257           ZFYVE26            TSS1500
8103  cg24016939 -0.524968            ZNF671             TSS200

[239 rows x 4 columns]

In [3]:
liquid_GSE89093=pd.read_csv("../result/all_beta_value_GSE89093_TSS_hyper_norepeate.csv")
liquid_label_GSE89093=pd.read_csv("../../乳癌液態/GSE89093/GSE89093_all_beta_normalized.csv")
liquid_label_GSE89093= liquid_label_GSE89093[liquid_label_GSE89093['0'].isin(['dummy'])].iloc[:,1::]
liquid_GSE89093= liquid_GSE89093[liquid_GSE89093['ID'].isin(gene_dbeta['ID'])]
liquid_GSE89093

c:\Users\Administrator\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ID,0,1,2,3,4,5,6,7,8,...,82,83,84,85,86,87,88,89,90,91
3,cg06971602,0.003002,0.010811,0.013308,0.005814,0.009736,0.005588,0.005619,0.005020,0.007565,...,0.009389,0.003772,0.005537,0.003712,0.016642,0.011005,0.006844,0.012846,0.008470,0.004217
24,cg05886574,0.003178,0.013077,0.016605,0.006741,0.003575,0.009534,0.008019,0.008827,0.002602,...,0.006036,0.005957,0.008155,0.005624,0.017981,0.008687,0.007982,0.009087,0.009624,0.006017
43,cg10739033,0.000545,0.008681,0.017915,0.004177,0.004893,0.013536,0.005007,0.002617,0.001637,...,0.006605,0.005920,0.007581,0.005628,0.006103,0.006063,0.018004,0.010055,0.012954,0.003549
46,cg15517836,0.002055,0.010825,0.011043,0.006231,0.003373,0.007236,0.005208,0.006348,0.003210,...,0.004838,0.006063,0.009408,0.007317,0.009100,0.010654,0.009807,0.010531,0.009774,0.004520
55,cg06253734,0.004207,0.011494,0.013724,0.007477,0.004421,0.010578,0.006849,0.004385,0.003634,...,0.007074,0.003319,0.008228,0.006598,0.010213,0.011568,0.008518,0.006897,0.006830,0.005554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3842,cg03642224,0.004764,0.006652,0.018130,0.008820,0.003661,0.014348,0.006528,0.004709,0.003621,...,0.007508,0.006267,0.011404,0.007048,0.009807,0.008253,0.010855,0.005558,0.010429,0.009706
3845,cg27417922,0.005084,0.008437,0.014290,0.002487,0.001695,0.011257,0.005202,0.005735,0.003803,...,0.000145,0.004097,0.008506,0.005211,0.013106,0.015418,0.007989,0.005238,0.005448,0.010521
3855,cg12600418,0.008429,0.018231,0.017987,0.008830,0.005222,0.011656,0.007474,0.002877,0.004110,...,0.002753,0.006373,0.006480,0.001609,0.007055,0.002964,0.014732,0.017367,0.017004,0.006304
3866,cg21861211,0.002308,0.017120,0.021686,0.009864,0.004582,0.006372,0.005217,0.006464,0.002670,...,0.007573,0.003590,0.007996,0.004215,0.011543,0.013367,0.009214,0.011397,0.009147,0.010174
3908,cg24016939,0.001864,0.010183,0.013138,0.003601,0.002271,0.006593,0.001171,0.003154,0.004167,...,0.004877,0.002077,0.002900,0.003072,0.002533,0.004177,0.004510,0.004873,0.004475,0.003713

In [4]:
liquid_normal_GSE89093 = []
liquid_tumor_GSE89093 = []
for i in range(liquid_label_GSE89093.shape[1]):
    if liquid_label_GSE89093.iloc[0, i] == 'healthy':
        liquid_normal_GSE89093.append(liquid_GSE89093.iloc[:,i+1])
    else:
        liquid_tumor_GSE89093.append(liquid_GSE89093.iloc[:,i+1])
        
liquid_normal_GSE89093=pd.DataFrame(liquid_normal_GSE89093).T
liquid_tumor_GSE89093=pd.DataFrame(liquid_tumor_GSE89093).T
liquid_normal_GSE89093 = liquid_normal_GSE89093.astype(float)
liquid_tumor_GSE89093 = liquid_tumor_GSE89093.astype(float)
liquid_tumor_GSE89093=pd.concat([liquid_GSE89093.iloc[:, 0],liquid_tumor_GSE89093], axis=1)
liquid_normal_GSE89093=pd.concat([liquid_GSE89093.iloc[:, 0],liquid_normal_GSE89093], axis=1)

In [5]:
train_normal_avg = liquid_normal_GSE89093.iloc[:,1::].mean(skipna=True, axis=1)
tt_dbeta=(liquid_tumor_GSE89093.iloc[:,1::]).subtract(train_normal_avg, axis = 0)
tt_dbeta

,1,4,6,7,8,10,14,15,16,19,...,71,73,75,78,79,82,83,85,90,91
3,0.002482,0.001407,-0.002710,-0.003308,-0.000764,-0.003155,0.002722,0.002510,-0.000020,0.001493,...,-0.003184,-0.001124,0.005088,0.004179,0.004012,0.001060,-0.004557,-0.004616,0.000142,-0.004112
24,0.003547,-0.005954,-0.001511,-0.000702,-0.006928,-0.002715,0.000279,-0.002524,-0.003514,-0.002382,...,-0.004909,0.000177,0.005831,0.005354,0.002713,-0.003493,-0.003572,-0.003905,0.000095,-0.003512
43,-0.000669,-0.004457,-0.004343,-0.006733,-0.007712,0.000156,-0.001016,-0.001877,-0.006221,-0.002608,...,-0.004115,0.002424,0.003082,0.003033,0.003009,-0.002745,-0.003430,-0.003722,0.003604,-0.005801
46,0.003169,-0.004283,-0.002448,-0.001308,-0.004446,-0.000104,0.001173,-0.002534,-0.001919,-0.003132,...,-0.002514,-0.000647,0.003486,0.004831,-0.002655,-0.002818,-0.001593,-0.000339,0.002117,-0.003136
55,0.002190,-0.004882,-0.002454,-0.004918,-0.005670,0.001218,0.007505,0.004685,-0.001975,0.003093,...,-0.003474,0.001076,0.012420,-0.001159,-0.001274,-0.002229,-0.005984,-0.002706,-0.002473,-0.003750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3842,-0.003010,-0.006000,-0.003133,-0.004952,-0.006040,-0.003064,0.004199,-0.002841,-0.002206,-0.001317,...,-0.001275,-0.004935,0.000448,0.004518,0.002129,-0.002153,-0.003394,-0.002613,0.000768,0.000045
3845,0.000243,-0.006499,-0.002992,-0.002459,-0.004390,0.000558,-0.004425,0.001858,-0.003375,0.005914,...,-0.003611,-0.003912,0.007305,0.001458,0.001454,-0.008048,-0.004096,-0.002983,-0.002746,0.002327
3855,0.009027,-0.003982,-0.001730,-0.006327,-0.005095,-0.007529,0.000253,-0.002475,0.000253,0.006462,...,-0.000209,-0.000640,0.010788,0.004771,0.011375,-0.006452,-0.002831,-0.007596,0.007799,-0.002900
3866,0.007410,-0.005128,-0.004492,-0.003245,-0.007039,-0.003640,-0.000456,0.000827,-0.004429,-0.001546,...,-0.006228,-0.002616,0.006555,0.003977,-0.000252,-0.002136,-0.006120,-0.005494,-0.000563,0.000464
3908,0.005648,-0.002264,-0.003364,-0.001381,-0.000368,0.000687,0.008025,0.000828,-0.001285,-0.001982,...,-0.003456,-0.002673,0.002099,-0.001401,0.002053,0.000342,-0.002458,-0.001463,-0.000060,-0.000822

In [6]:
avg_tumordBeta = tt_dbeta.mean(axis=1) #avg( Δβ (tumor) ) 
methylation_level_df = pd.DataFrame({'ID': liquid_GSE89093['ID'], 'methylation_level': avg_tumordBeta.apply(lambda x: 'Hyper' if x > 0 else 'Hypo')})
methylation_level_df

              ID methylation_level
3     cg06971602             Hyper
24    cg05886574              Hypo
43    cg10739033              Hypo
46    cg15517836             Hyper
55    cg06253734              Hypo
...          ...               ...
3842  cg03642224              Hypo
3845  cg27417922             Hyper
3855  cg12600418             Hyper
3866  cg21861211              Hypo
3908  cg24016939             Hyper

[239 rows x 2 columns]

In [7]:
merged_df = pd.merge(gene_dbeta, methylation_level_df, on='ID', how='inner')
merged_df.to_csv("../result/result_regulation_dbeta_0.52_liquid.csv",index=False)