In [1]:
import pandas as pd

In [3]:

df_filter =pd.read_csv('../../資料整理/3_train_dbeta_0.35.csv')
df_filter

             ID     dbeta     gene
0    cg13670057  0.359170     ABL1
1    cg10266490  0.403402   ACOT11
2    cg10976772  0.365513    ACOT7
3    cg18770350  0.375086    ACTN2
4    cg09499849  0.383661    ACVR1
..          ...       ...      ...
383  cg04738965  0.408686     ZIC1
384  cg16768018  0.462100     ZIC4
385  cg20985450  0.402938     ZIC5
386  cg21183523  0.381336   ZNF521
387  cg14231297  0.401591  ZSCAN18

[388 rows x 3 columns]

In [4]:
train=pd.read_csv('../../all_beta_normalized_train.csv')

In [7]:
df_gene = train[train['Unnamed: 0'].isin(df_filter['ID'])]
df_gene.reset_index(drop=True, inplace=True)
print(df_gene.shape)
df_gene.head()

(388, 891)

,Unnamed: 0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
0,cg03520644,0.229817,0.229817,0.079642,0.079642,0.180363,0.180363,0.182330,0.182330,0.156993,...,0.787966,0.787966,0.717043,0.717043,0.732963,0.732963,0.653539,0.653539,0.324511,0.324511
1,cg05047401,0.291908,0.291908,0.030616,0.030616,0.219142,0.219142,0.228138,0.228138,0.164601,...,0.790363,0.790363,0.774816,0.774816,0.738141,0.738141,0.780185,0.780185,0.721786,0.721786
2,cg06355129,0.232184,0.232184,0.261523,0.261523,0.176360,0.176360,0.253273,0.253273,0.083640,...,0.913858,0.913858,0.757479,0.757479,0.796541,0.796541,0.798998,0.798998,0.744522,0.744522
3,cg07790615,0.029336,0.029336,0.031738,0.031738,0.052790,0.052790,0.075713,0.075713,0.052144,...,0.793958,0.793958,0.713349,0.713349,0.809180,0.809180,0.798897,0.798897,0.584788,0.584788
4,cg09106903,0.091505,0.091505,0.066134,0.066134,0.126135,0.126135,0.094016,0.094016,0.039025,...,0.726509,0.726509,0.795497,0.795497,0.632736,0.632736,0.779592,0.779592,0.643527,0.643527

In [8]:
train_normal = df_gene.iloc[:,1:94:2]
train_tumor = df_gene.iloc[:,94::2]

train_tumor.columns=range(0,train_tumor.shape[1])
train_normal.columns=range(0,train_normal.shape[1])

train_tumor = train_tumor.T
train_normal = train_normal.T

In [9]:
train_normal_avg = train_normal.mean(skipna=True, axis=0)
tt_dbeta=(train_tumor).subtract(train_normal_avg, axis = 1)

In [10]:
tt_dbeta #tumor delta beta

,0,1,2,3,4,5,6,7,8,9,...,378,379,380,381,382,383,384,385,386,387
0,0.002722,0.159005,-0.074853,-0.017650,-0.020078,-0.040330,0.120806,-0.020801,-0.049774,0.090429,...,-0.100359,0.024904,0.023625,-0.026049,0.120544,-0.149759,-0.011675,0.022688,-0.086617,-0.010292
1,0.389678,0.465189,0.542915,0.286332,-0.042442,-0.033815,0.248216,0.134212,0.716888,0.309457,...,-0.001722,-0.472042,0.068169,0.458086,0.540094,-0.085528,0.575783,0.470906,0.100288,0.094093
2,0.252075,0.175216,-0.123224,0.291589,0.057750,-0.036066,-0.021861,0.018924,0.312647,0.414744,...,-0.429717,-0.406133,-0.027593,0.301364,-0.114673,-0.356939,0.169272,0.365579,0.451684,0.314283
3,0.476008,0.537575,0.568644,0.669520,0.572042,0.699485,0.581460,0.567749,0.719191,0.659896,...,-0.658007,-0.687373,0.631484,0.639570,0.619501,-0.260103,0.606957,0.627974,0.696148,0.746992
4,0.588893,0.524286,0.565482,0.658430,0.426472,0.630411,0.565579,0.700177,0.783661,0.623989,...,-0.546276,-0.697865,0.451131,0.602240,0.611190,-0.615514,0.669343,0.567665,0.676229,0.728267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,0.572551,0.520178,0.703143,0.725358,0.599171,0.685983,0.636285,0.675907,0.786011,0.649860,...,-0.189605,-0.550418,0.593598,0.614020,0.580360,-0.358228,0.651529,0.472912,0.731291,0.592605
395,0.501627,0.504631,0.546765,0.644750,0.668159,0.558093,0.616556,0.578003,0.740482,0.618489,...,-0.353336,-0.475268,0.449139,0.135412,0.553494,-0.256033,0.515776,0.560417,0.520019,0.321048
396,0.517547,0.467956,0.585826,0.740581,0.505398,0.652302,0.614133,0.734720,0.703586,0.475552,...,-0.549868,-0.531522,0.548960,0.503054,0.560129,-0.557767,0.617468,0.543598,0.640912,0.042638
397,0.438123,0.510000,0.588283,0.730298,0.652255,0.702540,0.594839,0.761389,0.759065,0.602627,...,-0.550420,-0.418239,0.630213,0.621442,0.581819,-0.521292,0.648855,0.544397,0.631176,0.667682
398,0.109095,0.451602,0.533807,0.516189,0.516189,0.513884,0.378469,0.028979,0.563690,0.522391,...,-0.449940,-0.444048,0.347016,0.406864,0.374154,-0.573933,0.338432,0.337987,0.252849,0.252383

標註Hyper/Hypo

In [13]:
avg_tumordBeta = tt_dbeta.mean(axis=0) #avg( Δβ (tumor) ) 
avg_tumordBeta

0      0.348612
1      0.401801
2      0.374405
3      0.449935
4      0.349763
         ...
383   -0.381687
384    0.346137
385    0.369598
386    0.361652
387    0.344138
Length: 388, dtype: float64

In [19]:
methylation_level_df = pd.DataFrame({'ID': df_gene['Unnamed: 0'], 'methylation_level': avg_tumordBeta.apply(lambda x: 'Hyper' if x > 0 else 'Hypo')})
methylation_level_df

             ID methylation_level
0    cg03520644             Hyper
1    cg05047401             Hyper
2    cg06355129             Hyper
3    cg07790615             Hyper
4    cg09106903             Hyper
..          ...               ...
383  cg15242225              Hypo
384  cg19678828             Hyper
385  cg00058879             Hyper
386  cg07879739             Hyper
387  cg20486569             Hyper

[388 rows x 2 columns]

In [20]:
cp_data=pd.read_csv('../result/result_basic_dbeta_0.35.csv')
cp_data.rename(columns={'Unnamed: 0': 'ID'}, inplace=True)
cp_data

,ID,dbeta,gene,"J,J","J,CZ","J,ER","J,F1","CZ,J","CZ,CZ","CZ,ER",...,Type,feature,cgi,feat.cgi,UCSC_CpG_Islands_Name,DHS,Enhancer,Phantom,Probe_SNPs,Probe_SNPs_10
0,cg13670057,0.359170,ABL1,0.8400,0.8400,0.8525,0.8400,0.84600,0.84600,0.85775,...,II,Body,opensea,Body-opensea,NaN,NaN,True,NaN,NaN,NaN
1,cg10266490,0.403402,ACOT11,0.6750,0.6750,0.6750,0.6750,0.70090,0.70090,0.70090,...,II,TSS200,opensea,TSS200-opensea,NaN,NaN,NaN,NaN,NaN,NaN
2,cg10976772,0.365513,ACOT7,0.7025,0.7025,0.6750,0.7025,0.72365,0.72365,0.69810,...,II,Body,opensea,Body-opensea,NaN,True,True,NaN,NaN,NaN
3,cg18770350,0.375086,ACTN2,0.7600,0.7600,0.7050,0.7600,0.77400,0.77400,0.72570,...,I,1stExon,island,1stExon-island,chr1:236849472-236850323,True,True,high-CpG:234916417-234916759,NaN,NaN
4,cg09499849,0.383661,ACVR1,0.6875,0.6875,0.6875,0.6875,0.71060,0.71060,0.71060,...,II,5'UTR,opensea,5'UTR-opensea,NaN,NaN,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,cg04738965,0.408686,ZIC1,0.7925,0.7925,0.8025,0.7925,0.79625,0.79625,0.80880,...,I,1stExon,island,1stExon-island,chr3:147126988-147128999,True,True,NaN,NaN,NaN
384,cg16768018,0.462100,ZIC4,0.7375,0.7375,0.7475,0.7375,0.74965,0.74965,0.75905,...,I,Body,island,Body-island,chr3:147108511-147111703,NaN,NaN,NaN,NaN,NaN
385,cg20985450,0.402938,ZIC5,0.7725,0.7725,0.6675,0.6675,0.78540,0.78540,0.68970,...,I,Body,island,Body-island,chr13:100620241-100624348,NaN,NaN,NaN,NaN,rs61080730
386,cg21183523,0.381336,ZNF521,0.6225,0.6225,0.4425,0.6225,0.64630,0.64630,0.50995,...,II,Body,shore,Body-shore,chr18:22930018-22930904,NaN,NaN,NaN,NaN,NaN
387,cg14231297,0.401591,ZSCAN18,0.6925,0.6925,0.6275,0.6925,0.70320,0.70320,0.66005,...,I,TSS200,island,TSS200-island,chr19:58629309-58630241,NaN,NaN,NaN,rs8109359,NaN

In [21]:
merged_df = pd.merge(cp_data, methylation_level_df, on='ID', how='inner')
merged_df

,ID,dbeta,gene,"J,J","J,CZ","J,ER","J,F1","CZ,J","CZ,CZ","CZ,ER",...,feature,cgi,feat.cgi,UCSC_CpG_Islands_Name,DHS,Enhancer,Phantom,Probe_SNPs,Probe_SNPs_10,methylation_level
0,cg13670057,0.359170,ABL1,0.8400,0.8400,0.8525,0.8400,0.84600,0.84600,0.85775,...,Body,opensea,Body-opensea,NaN,NaN,True,NaN,NaN,NaN,Hyper
1,cg10266490,0.403402,ACOT11,0.6750,0.6750,0.6750,0.6750,0.70090,0.70090,0.70090,...,TSS200,opensea,TSS200-opensea,NaN,NaN,NaN,NaN,NaN,NaN,Hyper
2,cg10976772,0.365513,ACOT7,0.7025,0.7025,0.6750,0.7025,0.72365,0.72365,0.69810,...,Body,opensea,Body-opensea,NaN,True,True,NaN,NaN,NaN,Hyper
3,cg18770350,0.375086,ACTN2,0.7600,0.7600,0.7050,0.7600,0.77400,0.77400,0.72570,...,1stExon,island,1stExon-island,chr1:236849472-236850323,True,True,high-CpG:234916417-234916759,NaN,NaN,Hyper
4,cg09499849,0.383661,ACVR1,0.6875,0.6875,0.6875,0.6875,0.71060,0.71060,0.71060,...,5'UTR,opensea,5'UTR-opensea,NaN,NaN,True,NaN,NaN,NaN,Hyper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,cg04738965,0.408686,ZIC1,0.7925,0.7925,0.8025,0.7925,0.79625,0.79625,0.80880,...,1stExon,island,1stExon-island,chr3:147126988-147128999,True,True,NaN,NaN,NaN,Hyper
384,cg16768018,0.462100,ZIC4,0.7375,0.7375,0.7475,0.7375,0.74965,0.74965,0.75905,...,Body,island,Body-island,chr3:147108511-147111703,NaN,NaN,NaN,NaN,NaN,Hyper
385,cg20985450,0.402938,ZIC5,0.7725,0.7725,0.6675,0.6675,0.78540,0.78540,0.68970,...,Body,island,Body-island,chr13:100620241-100624348,NaN,NaN,NaN,NaN,rs61080730,Hyper
386,cg21183523,0.381336,ZNF521,0.6225,0.6225,0.4425,0.6225,0.64630,0.64630,0.50995,...,Body,shore,Body-shore,chr18:22930018-22930904,NaN,NaN,NaN,NaN,NaN,Hyper
387,cg14231297,0.401591,ZSCAN18,0.6925,0.6925,0.6275,0.6925,0.70320,0.70320,0.66005,...,TSS200,island,TSS200-island,chr19:58629309-58630241,NaN,NaN,NaN,rs8109359,NaN,Hyper

計算Up/Down regulation(使用F1 cutpoint為基準)

In [22]:
cp=pd.read_csv("../../資料整理/1_388gene_cutpoint.csv")
cp

,J,J cut-point,J sensitivity,J specificity,CZ,CZ cut-point,CZ sensitivity,CZ specificity,ER,ER cut-point,ER sensitivity,ER specificity,F1,F1 cut-point,F1 sensitivity,F1 specificity,AUC
0,0.872180,0.16,0.997494,0.106383,0.872180,0.16,0.997494,0.106383,0.124636,0.15,0.997494,0.106383,0.931727,0.16,0.997494,0.106383,0.854743
1,0.893510,0.25,1.000000,0.063830,0.895323,0.25,1.000000,0.063830,0.087829,0.25,1.000000,0.063830,0.945676,0.25,1.000000,0.063830,0.915827
2,0.840879,0.12,0.984962,0.106383,0.843812,0.12,0.984962,0.106383,0.131504,0.10,0.984962,0.106383,0.916749,0.12,0.984962,0.106383,0.838026
3,0.854637,0.12,0.979950,0.212766,0.854637,0.12,0.979950,0.212766,0.143299,0.06,0.979950,0.212766,0.921622,0.12,0.979950,0.212766,0.737135
4,0.764464,0.11,0.977444,0.106383,0.772676,0.11,0.977444,0.106383,0.197618,0.11,0.977444,0.106383,0.875820,0.11,0.977444,0.106383,0.793393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,0.819549,0.20,0.994987,0.042553,0.819549,0.20,0.994987,0.042553,0.161058,0.17,0.994987,0.042553,0.900826,0.20,0.994987,0.042553,0.890071
384,0.798272,0.14,0.982456,0.127660,0.802112,0.14,0.982456,0.127660,0.180526,0.13,0.982456,0.127660,0.892091,0.14,0.982456,0.127660,0.800005
385,0.869674,0.19,0.992481,0.127660,0.869674,0.19,0.992481,0.127660,0.114771,0.17,0.992481,0.127660,0.930727,0.17,0.992481,0.127660,0.826214
386,0.682984,0.22,0.972431,0.021277,0.689276,0.22,0.972431,0.021277,0.266849,0.11,0.972431,0.021277,0.819112,0.22,0.972431,0.021277,0.835200
387,0.668000,0.14,0.967419,0.106383,0.685117,0.14,0.967419,0.106383,0.267954,0.10,0.967419,0.106383,0.821483,0.14,0.967419,0.106383,0.769130

In [25]:
import numpy as np
cut_point = cp["F1 cut-point"]

regulation = pd.DataFrame({
    'ID': df_gene['Unnamed: 0'],
    'regulation': np.where(avg_tumordBeta > cut_point, 'Up', 'Down')
})
regulation

             ID regulation
0    cg03520644         Up
1    cg05047401         Up
2    cg06355129         Up
3    cg07790615         Up
4    cg09106903         Up
..          ...        ...
383  cg15242225       Down
384  cg19678828         Up
385  cg00058879         Up
386  cg07879739         Up
387  cg20486569         Up

[388 rows x 2 columns]

In [26]:
merged_df=pd.merge(merged_df, regulation, on='ID', how='inner')
merged_df

,ID,dbeta,gene,"J,J","J,CZ","J,ER","J,F1","CZ,J","CZ,CZ","CZ,ER",...,cgi,feat.cgi,UCSC_CpG_Islands_Name,DHS,Enhancer,Phantom,Probe_SNPs,Probe_SNPs_10,methylation_level,regulation
0,cg13670057,0.359170,ABL1,0.8400,0.8400,0.8525,0.8400,0.84600,0.84600,0.85775,...,opensea,Body-opensea,NaN,NaN,True,NaN,NaN,NaN,Hyper,Up
1,cg10266490,0.403402,ACOT11,0.6750,0.6750,0.6750,0.6750,0.70090,0.70090,0.70090,...,opensea,TSS200-opensea,NaN,NaN,NaN,NaN,NaN,NaN,Hyper,Up
2,cg10976772,0.365513,ACOT7,0.7025,0.7025,0.6750,0.7025,0.72365,0.72365,0.69810,...,opensea,Body-opensea,NaN,True,True,NaN,NaN,NaN,Hyper,Up
3,cg18770350,0.375086,ACTN2,0.7600,0.7600,0.7050,0.7600,0.77400,0.77400,0.72570,...,island,1stExon-island,chr1:236849472-236850323,True,True,high-CpG:234916417-234916759,NaN,NaN,Hyper,Up
4,cg09499849,0.383661,ACVR1,0.6875,0.6875,0.6875,0.6875,0.71060,0.71060,0.71060,...,opensea,5'UTR-opensea,NaN,NaN,True,NaN,NaN,NaN,Hyper,Up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,cg04738965,0.408686,ZIC1,0.7925,0.7925,0.8025,0.7925,0.79625,0.79625,0.80880,...,island,1stExon-island,chr3:147126988-147128999,True,True,NaN,NaN,NaN,Hyper,Up
384,cg16768018,0.462100,ZIC4,0.7375,0.7375,0.7475,0.7375,0.74965,0.74965,0.75905,...,island,Body-island,chr3:147108511-147111703,NaN,NaN,NaN,NaN,NaN,Hyper,Up
385,cg20985450,0.402938,ZIC5,0.7725,0.7725,0.6675,0.6675,0.78540,0.78540,0.68970,...,island,Body-island,chr13:100620241-100624348,NaN,NaN,NaN,NaN,rs61080730,Hyper,Up
386,cg21183523,0.381336,ZNF521,0.6225,0.6225,0.4425,0.6225,0.64630,0.64630,0.50995,...,shore,Body-shore,chr18:22930018-22930904,NaN,NaN,NaN,NaN,NaN,Hyper,Up
387,cg14231297,0.401591,ZSCAN18,0.6925,0.6925,0.6275,0.6925,0.70320,0.70320,0.66005,...,island,TSS200-island,chr19:58629309-58630241,NaN,NaN,NaN,rs8109359,NaN,Hyper,Up

In [ ]:
merged_df.to_csv("../result/result_regulation_dbeta_0.35.csv",index=False)